[window]
opacity = 0.9
decorations = "Full"
dynamic_padding = false

[window.dimensions]
columns = 80
lines = 22

[window.position]
x = 400
y = 220

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
size = 13

[colors.primary]
background = "#2c2525"
foreground = "#fff1f3"

[colors.normal]
black   = "#2c2525"
red     = "#fd6883"
green   = "#adda78"
yellow  = "#f9cc6c"
blue    = "#f38d70"
magenta = "#a8a9eb"
cyan    = "#85dacc"
white   = "#fff1f3"

[colors.bright]
black   = "#72696a"
red     = "#fd6883"
green   = "#adda78"
yellow  = "#f9cc6c"
blue    = "#f38d70"
magenta = "#a8a9eb"
cyan    = "#85dacc"
white   = "#fff1f3"

[colors.cursor]
cursor = "#f5c2e7"
text = "#1e1e2e"

[scrolling]
history = 10000

[terminal]
# NOTE: fish is not compatible with POSIX sh!
# So instead of chsh to it, it's better to use it on terminal emulators only.
shell="fish"

[env]
# alacritty is not recognized as a terminal emulator by some programs
# avoid issues by setting TERM to xterm-256color
TERM = "xterm-256color"

[general]
live_config_reload = true
